#!/bin/bash

echo "========================================"
echo "   Bridge Connection Diagnostics"
echo "========================================"

echo ""
echo "--- 1. 检查Gazebo端是否有scan话题 ---"
echo "执行: ign topic -l | grep scan"
ign topic -l 2>/dev/null | grep scan || echo "❌ 没有scan话题（这是问题根源！）"

echo ""
echo "--- 2. 检查所有Gazebo话题 ---"
echo "执行: ign topic -l"
ign topic -l 2>/dev/null | head -20 || echo "无法列出Gazebo话题"

echo ""
echo "--- 3. 检查桥接节点详情 ---"
echo "执行: ros2 node info /front_lidar_bridge"
ros2 node info /front_lidar_bridge 2>/dev/null || echo "front_lidar_bridge节点不存在"

echo ""
echo "--- 4. 检查Gazebo模型列表 ---"
echo "执行: ign model -l"
ign model -l 2>/dev/null || echo "无法列出模型"

echo ""
echo "--- 5. 检查传感器列表 ---"
echo "执行: gz sensor -l"
gz sensor -l 2>/dev/null | grep -i scan || echo "没有scan传感器"

echo ""
echo "--- 6. 检查URDF是否包含传感器 ---"
echo "检查robot_description参数中的sensor配置"
ros2 param get /robot_state_publisher robot_description 2>/dev/null | grep -A 5 "front_lidar" || echo "robot_state_publisher没有传感器配置"

echo ""
echo "========================================"
echo "       问题分析"
echo "========================================"
echo ""
echo "如果 'ign topic -l | grep scan' 没有输出，说明："
echo "  ❌ Gazebo传感器没有发布数据"
echo ""
echo "可能原因："
echo "  1. 模型资源文件未正确加载"
echo "  2. 传感器初始化失败"
echo "  3. 传感器链接未正确附加到模型"
echo "  4. Gazebo sensors-system插件未正常工作"
echo ""
echo "请检查上述输出，找出具体原因。"